yatube/posts/urls.py
from django import views
from django.urls import path
from . import views

app_name  = 'posts'

urlpatterns = [
    path('', views.index, name='main'),
    path('group/<slug:pk>/', views.group_posts, name='group')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.


User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length = 250)
    slug = models.SlugField(max_length = 50)
    description = models.TextField()


    def __str__(cls):
        return cls.title
        
class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

    author = models.ForeignKey(
        User,
        on_delete = models.CASCADE,
        related_name= 'posts' 
    )

    group = models.ForeignKey( Group, blank=True, null=True,
     on_delete=models.CASCADE)

yatube/posts/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Post



# Create your views here.

#def index(request):
#    context = {'title':"Это главная страница проекта Yatube"}
#    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    
    posts = Post.objects.filter('').order_by('-pub_date')[:10]
    context = {'title':
        f"Посты группы: {slug}",
        'posts' : posts}
    return render(request, 'posts/group_list.html', context)

def index(request):
    # Одна строка вместо тысячи слов на SQL:
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию (от больших значений к меньшим)
    posts = Post.objects.order_by('-pub_date')[:10]
    # В словаре context отправляем информацию в шаблон
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context) 

yatube/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html> 
<html lang="ru">          
  <header>
    {% include 'includes/header.html' %}
  </header>
  <body>       
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    

yatube/templates/includes/header.html
<head> 


<meta charset="utf-8"> <!-- Кодировка сайта -->
<!-- Сайт готов работать с мобильными устройствами -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Загружаем фав-иконки -->
<link rel="icon" href="img/fav/fav.ico" type="image">
{% load static %}
<img src="{% static 'img/logo.png' %}"> 
<link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
<meta name="msapplication-TileColor" content="#000">
<meta name="theme-color" content="#ffffff">
<!-- Подключен файл со стандартными стилями бустрап -->
<link rel="stylesheet" href="css/bootstrap.min.css">
{%block title%}      {% endblock %}

</head>

yatube/templates/posts/group_list.html
{%extends 'base.html' %}

{%block title%}
<title>{{title}}</title>
{%endblock%}

{% block content %}
<main>
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1>>{{title}}</h1>
    <p>
      Группа тайных поклонников графа.
    </p>
    <article>
      <ul>
        <li>
          Автор: Лев Толстой
        </li>
        <li>
          Дата публикации: 30 июля 1854
        </li>
      </ul>      
      <p>
        [Рымник.] Сдѣлалъ верхомъ переходъ до Рымника. [[5]] Старикъ все не кланяется мнѣ.
        Обѣ вещи эти злятъ меня. Съ встрѣчавшимися баши-бузуками велъ себя хорошо. 
        Объяснился съ Крыжановскимъ. Онъ, не знаю зачѣмъ, совѣтуетъ мнѣ прикомандироваться 
        къ казачьей батареѣ; совѣтъ, которому я не послѣдую. Желчно спорилъ вечеромъ съ Фриде 
        и Бабарыкинымъ, ругалъ Сержпутовскому и ничего не сдѣлалъ, вотъ 3 упрека, которыя дѣлаю с
        ебѣ за нынѣшній день. (3)
      </p>         
    </article>
    <hr>
    <article>
      <ul>
        <li>
          Автор: Лев Толстой
        </li>
        <li>
          Дата публикации: 29 июля 1854
        </li>
      </ul> 
      <p>
        Исправленіе мое идетъ прекрасно. Я чувствую, какъ отношенія мои становятся пріятны и легки 
        съ людьми всякаго рода, съ тѣхъ поръ какъ я рѣшился быть скромнымъ и убѣдился въ томъ, 
        что казаться всегда величественнымъ и непогрѣшнымъ вовсе не есть необходимость. Я очень 
        веселъ. И дай Богъ, какъ мнѣ кажется, — чтобы веселье это происходило отъ самаго меня; 
        отъ желаній всѣмъ быть пріятнымъ, скромности, необидчивости и внимательности за вспышками. 
        — Тогда бы я всегда былъ веселъ и почти всегда счастливъ. 
        Утромъ рѣшилъ было сидѣть дома, позаниматься, но дѣло не пошло и не утерпѣлъ вечеромъ, 
        чтобы не пойдти пошляться. Идя отъ ужина, мы съ Тишк[евичемъ] остановились у бардели и насъ 
        накрылъ Крыжановскій, что, признаюсь, было мнѣ не совсѣмъ пріятно. Упрекаю себя за 
        безхарактерность, что не высидѣлъ дома, и зa праздность цѣлаго дня. Это главный пунктъ. (2)
      </p>      
    </article>
    <hr>
    <article>
      <ul>
        <li>
          Автор: Лев Толстой
        </li>
        <li>
          Дата публикации: 28 июля 1854
        </li>
      </ul> 
      <p>
        Пишу въ самомъ пріятномъ веселомъ расположеніи духа, въ которомъ я провелъ весь вечеръ. 
        Утро читалъ, объѣдался грушами и вмѣсто обѣда ѣлъ сыръ. Несмотря на кутежи у Сталыпина и 
        Сержпутовскаго по случаю полученія наградъ, не завидовалъ, а провелъ день весело. Вечеромъ 
        хватилъ босонож[ку] и выпилъ бокала два шампанскаго съ Шварц[емъ], Вейлеровскимъ [?] и 
        Гембичомъ, потомъ болталъ съ Шубинымъ и съ Сашей Горчаковымъ. — Исключая праздности, 
        днемъ своимъ очень доволенъ. (1)
      </p>
    </article>
    <!-- под последним постом нет линии -->
  </div>  
</main>
{% endblock %} 

yatube/templates/posts/index.html
{%extends 'base.html'%}
{%block title%}
    <title>{{title}}</title>
{%endblock%}
<head>  
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
</head>
{%block content%}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1>{{title}}</h1>
        {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>    
        <a href="">все записи группы</a>
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        <a href="%{% url 'posts:group' 1 %}">все записи группы</a>
        <!-- под последним постом нет линии -->
      </div>  
{%endblock%}